### ISSUE TITLE
Should we create a rule for our stylelint config to force logical properties?

### ISSUE THREAD

**Issue by leroykorterink** [mediamonks/stylelint-config#2]
Logical CSS properties will control layout through logical, rather than physical, direction and dimension mappings. The CSS is more likely to work as expected in different writing-modes/directions if logical properties are used. So no custom plugins/build tools are needed to create a RTL layouts).

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties

Something like this: https://github.com/csstools/stylelint-use-logical could work. That repo isn’t up-to-date (missing a lot of properties) so we probably need to create something ourselves.

**Comment by psimk** [comment]
How many of our projects actually require the use of different writing-modes/directions? If it is the minority, do we really think that enforcing the use of logical properties for all projects, is a good idea?

I can already imagine a new developer being confused when they come on to a project as to why we are forcing them to using logical properties on a standard LTR project. We should teach developers when is the right time for certain tools in their toolkit, instead of enforcing a rule _just because_.

---

With that said, for the projects that would actually benefit from this - we could probably create a new stylelint config file that includes the main one and appends the logical property rules/plugin. Then it would be as easy as changing the `extends` in the local project `.stylelintrc`.

**Comment by leroykorterink** [comment]
Added `stylelint-use-logical`, closing the issue.
